type Reaction {
  id: ID!
  usuarioId: String!
  objetivoId: String!
  tipoObjetivo: String!
  tipoReaccion: TipoReaccion!
  createdAt: String
}

enum TipoReaccion {
  LIKE
  LOVE
  CELEBRATE
  SUPPORT
}

extend type Query {
  reactions(targetId: String!, targetType: String!): [Reaction!]!
  myReaction(userId: String!, targetId: String!, targetType: String!): Reaction
}

extend type Mutation {
  react(
    usuarioId: String!
    objetivoId: String!
    tipoObjetivo: String!
    tipoReaccion: TipoReaccion!
  ): Reaction
  unreact(usuarioId: String!, objetivoId: String!, tipoObjetivo: String!): Boolean
  changeReaction(
    usuarioId: String!
    objetivoId: String!
    tipoObjetivo: String!
    tipoReaccion: TipoReaccion!
  ): Reaction
}
