type RecruiterProfile {
  id: ID!
  userId: String!
  cargo: String
  ruc: String
  lema: String
  empresasDescripcion: String
  fechaCreacion: String
  modalidadTrabajo: ModalidadTrabajo
  redesSociales: RedesSociales
  empresas: [RecruiterEmpresa]
  verificado: Boolean
}

type RecruiterEmpresa {
  companyId: String
  cargoEnEmpresa: String
  activo: Boolean
}

type RedesSociales {
  linkedin: String
  instagram: String
  tiktok: String
  facebook: String
}

enum ModalidadTrabajo {
  PRESENCIAL
  HIBRIDO
  VIRTUAL
}

input RedesSocialesInput {
  linkedin: String
  instagram: String
  tiktok: String
  facebook: String
}

extend type Query {
  recruiterProfile(userId: String!): RecruiterProfile
  myRecruiterProfile: RecruiterProfile
}

extend type Mutation {
  createRecruiterProfile(
    userId: String!
    cargo: String
    ruc: String
    lema: String
    empresasDescripcion: String
    fechaCreacion: String
    modalidadTrabajo: ModalidadTrabajo
    redesSociales: RedesSocialesInput
  ): RecruiterProfile
  updateRecruiterProfile(
    id: ID!
    cargo: String
    ruc: String
    lema: String
    empresasDescripcion: String
    fechaCreacion: String
    modalidadTrabajo: ModalidadTrabajo
    redesSociales: RedesSocialesInput
  ): RecruiterProfile
}
