type Story {
  id: ID!
  autorId: String!
  contenido: StoryContenido
  visibilidad: String
  fechaExpiracion: String
  vistasCount: Int
  reaccionesCount: Int
  estado: String
  createdAt: String
}

type StoryContenido {
  texto: String
  imagenUrl: String
  videoUrl: String
  musica: StoryMusica
}

type StoryMusica {
  trackId: String
  trackName: String
  artistName: String
  coverUrl: String
  previewUrl: String
  musicMode: String
  lyricsText: String
  lyricsPosX: Float
  lyricsPosY: Float
  coverPosX: Float
  coverPosY: Float
  lyricsScale: Float
  coverScale: Float
}

type StoryView {
  id: ID!
  storyId: String!
  viewerId: String!
  viewedAt: String
}

extend type Query {
  stories(userId: String!): [Story!]!
  story(id: ID!): Story
  storyViews(storyId: String!): [StoryView!]!
}

extend type Mutation {
  createStory(
    autorId: String!
    contenido: StoryContenidoInput
    visibilidad: String
  ): Story
  viewStory(storyId: String!, viewerId: String!): StoryView
  deleteStory(id: ID!): Boolean
}

input StoryContenidoInput {
  texto: String
  imagenUrl: String
  videoUrl: String
  musica: StoryMusicaInput
}

input StoryMusicaInput {
  trackId: String
  trackName: String
  artistName: String
  coverUrl: String
  previewUrl: String
  musicMode: String
  lyricsText: String
  lyricsPosX: Float
  lyricsPosY: Float
  coverPosX: Float
  coverPosY: Float
  lyricsScale: Float
  coverScale: Float
}
