type User {
  id: ID!
  nombre: String!
  nombreUsuario: String!
  email: String!
  telefono: String
  fotoPerfilUrl: String
  bannerUrl: String
  bio: String
  sitioWeb: String
  ubicacion: UserUbicacion
  roles: [String!]!
  rolActivo: String
  estadoCuenta: String!
  emailVerificado: Boolean!
  seguidoresCount: Int
  siguiendoCount: Int
  conexionesCount: Int
  createdAt: String
  developerProfile: DeveloperProfile
  recruiterProfile: RecruiterProfile
}

type UserUbicacion {
  pais: String
  departamento: String
  provincia: String
  ciudad: String
  distrito: String
  direccion: String
}

extend type Query {
  me: User
  user(id: ID!): User
  users: [User!]!
}

extend type Mutation {
  updateUser(
    id: ID!
    nombre: String
    nombreUsuario: String
    email: String
    telefono: String
    fotoPerfilUrl: String
    bannerUrl: String
    bio: String
    sitioWeb: String
    ubicacion: UserUbicacionInput
  ): User
  updateNotificationPreferences(
    userId: ID!
    preferences: NotificationPreferencesInput
  ): User
  deleteUser(id: ID!): Boolean
}

input UserUbicacionInput {
  pais: String
  departamento: String
  provincia: String
  ciudad: String
  distrito: String
  direccion: String
}

input NotificationPreferencesInput {
  email: Boolean
  push: Boolean
  mensajes: Boolean
  comentarios: Boolean
  reacciones: Boolean
  conexiones: Boolean
  vacantes: Boolean
}
