type User {
  id: ID!
  nombre: String!
  nombreUsuario: String!
  email: String!
  telefono: String
  fotoPerfilUrl: String
  bannerUrl: String
  bio: String
  ubicacion: UserUbicacion
  roles: [String!]!
  rolActivo: String
  estadoCuenta: String!
  emailVerificado: Boolean!
  seguidoresCount: Int
  siguiendoCount: Int
  conexionesCount: Int
  createdAt: String
  developerProfile: DeveloperProfile
  recruiterProfile: RecruiterProfile
}

type UserUbicacion {
  pais: String
  ciudad: String
  distrito: String
}

extend type Query {
  me: User
  user(id: ID!): User
  users: [User!]!
}

extend type Mutation {
  updateUser(
    id: ID!
    nombre: String
    nombreUsuario: String
    email: String
    telefono: String
    fotoPerfilUrl: String
    bannerUrl: String
    bio: String
    ubicacion: UserUbicacionInput
  ): User
  deleteUser(id: ID!): Boolean
}

input UserUbicacionInput {
  pais: String
  ciudad: String
  distrito: String
}
