spring.application.name=comunidev-backend

# MongoDB Atlas
spring.data.mongodb.uri=mongodb+srv://solvegrades_db_user:bVVvSVOYvGjGnXL7@comunidevdb.j8ijkhj.mongodb.net/comunidevDB?retryWrites=true&w=majority&appName=comunidevDB

# Server
server.port=8080

# GraphQL
spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql
