spring.application.name=${SPRING_APP_NAME:comunidev-backend}

# MongoDB Atlas
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb+srv://solvegrades_db_user:bVVvSVOYvGjGnXL7@comunidevdb.j8ijkhj.mongodb.net/comunidevDB?retryWrites=true&w=majority&appName=comunidevDB}

# Server (Render asigna PORT)
server.port=${PORT:8080}

# GraphQL
spring.graphql.graphiql.enabled=${GRAPHQL_GRAPHIQL_ENABLED:true}
spring.graphql.graphiql.path=${GRAPHQL_GRAPHIQL_PATH:/graphiql}

# Swagger/OpenAPI
springdoc.swagger-ui.path=${SWAGGER_UI_PATH:/swagger-ui.html}
springdoc.api-docs.path=${API_DOCS_PATH:/v3/api-docs}

# GitHub OAuth
github.client.id=${GITHUB_CLIENT_ID:Ov23lid2BhD71ka9RkFD}
github.client.secret=${GITHUB_CLIENT_SECRET:0e7127ea53bcc2b6b840561c0176f3ae1727aff7}
github.redirect.uri=${GITHUB_REDIRECT_URI:http://localhost:8080/api/v1/auth/github/callback}
